from datetime import datetime, timedelta
from functools import wraps
from pathlib import Path

import jwt
from flask import jsonify, request

# Load secure JWT secret (generated by install.sh)
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
SECRET_FILE = _PROJECT_ROOT / "jwt_secret.txt"
SECRET: str = (
    SECRET_FILE.read_text(encoding="utf-8").strip()
    if SECRET_FILE.exists()
    else "mrvpn-jwt-secret-2026-fallback"  # only for very old installs
)

BLACKLIST: set = set()


def create_access_token() -> str:
    payload = {"exp": datetime.utcnow() + timedelta(hours=1), "type": "access"}
    return jwt.encode(payload, SECRET, algorithm="HS256")


def create_refresh_token() -> str:
    payload = {"exp": datetime.utcnow() + timedelta(days=3), "type": "refresh"}
    return jwt.encode(payload, SECRET, algorithm="HS256")


def verify_token(token: str, token_type: str = "access") -> bool:
    if token in BLACKLIST:
        return False
    try:
        payload = jwt.decode(token, SECRET, algorithms=["HS256"])
        return payload.get("type") == token_type
    except Exception:
        return False


def blacklist_token(token: str) -> None:
    BLACKLIST.add(token)


def require_auth(f):
    """Decorator that validates the Bearer JWT on every protected route."""

    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.headers.get("Authorization", "")
        token = auth.removeprefix("Bearer ").strip()
        if not verify_token(token, "access"):
            return jsonify({"ok": False, "error": "unauthorized"}), 401
        return f(*args, **kwargs)

    return decorated
